apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qaj4mf7q6-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:acfb8bdada4dc60d146dd2568200a7b0a5f883e7@sha256:a8c5275b24ac21bbddf0f5ae6c5046e7ca475133e7cbdd17e33b787eb6374bee
          name: container-image
